data = [
    {"name": "Lionel Messi", "follower_count": 115, "origin": "Argentina", "profession": "Football player"},
    {"name": "Cristiano Ronaldo", "follower_count": 150, "origin": "Portugal", "profession": "Football player"},
    {"name": "Neymar Jr", "follower_count": 110, "origin": "Brazil", "profession": "Football player"},
    {"name": "Kylian Mbappé", "follower_count": 80, "origin": "France", "profession": "Football player"},
    {"name": "Mohamed Salah", "follower_count": 60, "origin": "Egypt", "profession": "Football player"},
    {"name": "Kevin De Bruyne", "follower_count": 40, "origin": "Belgium", "profession": "Football player"},
    {"name": "Erling Haaland", "follower_count": 50, "origin": "Norway", "profession": "Football player"},
    {"name": "Robert Lewandowski", "follower_count": 35, "origin": "Poland", "profession": "Football player"},
    {"name": "Luka Modrić", "follower_count": 30, "origin": "Croatia", "profession": "Football player"},
    {"name": "Vinícius Júnior", "follower_count": 45, "origin": "Brazil", "profession": "Football player"},
    {"name": "Antoine Griezmann", "follower_count": 28, "origin": "France", "profession": "Football player"},
    {"name": "Sadio Mané", "follower_count": 25, "origin": "Senegal", "profession": "Football player"},
    {"name": "Jude Bellingham", "follower_count": 22, "origin": "England", "profession": "Football player"},
    {"name": "Marcus Rashford", "follower_count": 32, "origin": "England", "profession": "Football player"},
    {"name": "Paulo Dybala", "follower_count": 27, "origin": "Argentina", "profession": "Football player"},
    {"name": "Son Heung-min", "follower_count": 26, "origin": "South Korea", "profession": "Football player"},
    {"name": "Zlatan Ibrahimović", "follower_count": 38, "origin": "Sweden", "profession": "Football player"},

    {"name": "LeBron James", "follower_count": 150, "origin": "USA", "profession": "NBA player"},
    {"name": "Stephen Curry", "follower_count": 55, "origin": "USA", "profession": "NBA player"},
    {"name": "Kevin Durant", "follower_count": 40, "origin": "USA", "profession": "NBA player"},
    {"name": "Giannis Antetokounmpo", "follower_count": 30, "origin": "Greece", "profession": "NBA player"},
    {"name": "Luka Dončić", "follower_count": 25, "origin": "Slovenia", "profession": "NBA player"},
    {"name": "Ja Morant", "follower_count": 15, "origin": "USA", "profession": "NBA player"},
    {"name": "Jayson Tatum", "follower_count": 20, "origin": "USA", "profession": "NBA player"},
    {"name": "Kyrie Irving", "follower_count": 19, "origin": "USA", "profession": "NBA player"},

    {"name": "Dwayne Johnson", "follower_count": 390, "origin": "USA", "profession": "Actor"},
    {"name": "Tom Holland", "follower_count": 75, "origin": "UK", "profession": "Actor"},
    {"name": "Zendaya", "follower_count": 180, "origin": "USA", "profession": "Actor"},
    {"name": "Leonardo DiCaprio", "follower_count": 60, "origin": "USA", "profession": "Actor"},
    {"name": "Chris Hemsworth", "follower_count": 58, "origin": "Australia", "profession": "Actor"},
    {"name": "Emma Watson", "follower_count": 70, "origin": "UK", "profession": "Actor"},
    {"name": "Ryan Reynolds", "follower_count": 50, "origin": "Canada", "profession": "Actor"},
    {"name": "Margot Robbie", "follower_count": 45, "origin": "Australia", "profession": "Actor"}
]